# Generated by Django 5.2.7 on 2025-10-27 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='სახელი')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='სლაგი')),
                ('description', models.TextField(blank=True, null=True, verbose_name='აღწერა')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='სურათი')),
                ('is_active', models.BooleanField(default=True, verbose_name='აქტიურია?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='შექმნის თარიღი')),
            ],
            options={
                'verbose_name': 'კატეგორია',
                'verbose_name_plural': 'კატეგორიები',
                'ordering': ['name'],
            },
        ),
    ]
